definitions:
  quotation.GetCurrencyListResponse:
    properties:
      currencies:
        items:
          format: uuid
          type: string
        type: array
    type: object
  quotation.GetQuotationByRequestIdResponse:
    description: fields `price` and `timestamp` are only presented when status is
      `Ready`
    properties:
      rate:
        example: "123.45"
        format: decimal
        type: string
      status:
        $ref: '#/definitions/quotation.RequestStatus'
      updatedAt:
        description: Unix timestamp in milliseconds
        example: 1694613600
        format: int64
        type: integer
    required:
    - status
    type: object
  quotation.GetQuotationResponse:
    properties:
      rate:
        example: "123.45"
        format: decimal
        type: string
      updatedAt:
        description: Unix timestamp in milliseconds
        example: 1694613600
        format: int64
        type: integer
    type: object
  quotation.RequestQuotationUpdateBody:
    properties:
      baseCurrency:
        $ref: '#/definitions/types.Currency'
      idempotencyKey:
        format: uuid
        type: string
      quoteCurrency:
        $ref: '#/definitions/types.Currency'
    required:
    - baseCurrency
    - idempotencyKey
    - quoteCurrency
    type: object
  quotation.RequestQuotationUpdateResponse:
    properties:
      requestId:
        format: uuid
        type: string
    required:
    - requestId
    type: object
  quotation.RequestStatus:
    enum:
    - Ready
    - NotReady
    type: string
    x-enum-varnames:
    - Ready
    - NotReady
  response.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  types.Currency:
    enum:
    - USD
    - EUR
    - MXN
    type: string
    x-enum-varnames:
    - USD
    - EUR
    - MXN
info:
  contact: {}
paths:
  /api/v1/currency/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/quotation.GetCurrencyListResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get list of supported currencies
      tags:
      - Currency
  /api/v1/quotation/last-requested:
    get:
      description: Retrieves last requested quotation by base and quote currencies.
        Returns `404 Quotation not found` if quotation wasn't requested at least once,
        use `[post] /api/v1/update-request` in this case
      parameters:
      - description: Base Currency
        in: query
        name: base
        required: true
        type: string
      - description: Quote Currency
        in: query
        name: quote
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/quotation.GetQuotationResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Quotation not found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get last requested quotation by currencies
      tags:
      - Quotation
  /api/v1/quotation/update-request:
    post:
      consumes:
      - application/json
      description: Creates a quotation update request. Returns request Id.
      parameters:
      - description: Quotation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/quotation.RequestQuotationUpdateBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/quotation.RequestQuotationUpdateResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Request quotation update
      tags:
      - Quotation
  /api/v1/quotation/update-request/{id}:
    get:
      description: Retrieves a quotation by request Id. If request is not proceeded
        yet, returns status `NotReady`. If request is completed, returns status `Ready`
        and fields `rate` and `updatedAt`.
      parameters:
      - description: Quotation ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/quotation.GetQuotationByRequestIdResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: No request with such id
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get quotation by request Id
      tags:
      - Quotation
swagger: "2.0"
